import { Geist, Geist_Mono } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import "./globals.css";

import { Footer } from "./footer";
import { Header } from "./header";

import type { Metadata } from "next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  aside,
  children,
}: Readonly<{
  aside: React.ReactNode;
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} h-screen overflow-hidden antialiased`}
      >
        <NuqsAdapter>
          <div className="grid h-full w-full grid-rows-[auto_1fr_auto]">
            <Header />
            <main className="row-span-1 mx-auto grid h-full w-full max-w-7xl grid-cols-3 gap-8 px-4 py-16">
              {aside}
              {children}
            </main>
            <Footer />
          </div>
        </NuqsAdapter>
      </body>
    </html>
  );
}
